name: Update Fork Star

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 19 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: isjhd/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.METRICS_TOKEN }}
